Repository Ureca-Middle-Project-Team4/4EVER0-BE, pull requests merged in 2025-06, with the labels that each got.

#2 Feat: [EVER-6] 백엔드 레포 초기 설정
  .github/workflows/build.yml
  .gitignore
  .gitmessage.txt
  .idea/.gitignore
  .idea/.name
  .idea/4EVER0-BE.iml
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/backend.main.iml
  .idea/vcs.xml
  build.gradle
  src/main/java/com/team4ever/backend/BackendApplication.java
  src/main/java/com/team4ever/backend/global/config/SwaggerConfig.java
  src/main/java/com/team4ever/backend/global/exception/CustomException.java
  src/main/java/com/team4ever/backend/global/exception/ErrorCode.java
  src/main/java/com/team4ever/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/team4ever/backend/global/response/BaseResponse.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/team4ever/backend/BackendApplicationTests.java
Labels: ⚙ Setting

#12 Fix: [EVER-29] 지라 빌드를 위한 메인으로 merge용
  .github/ISSUE_TEMPLATE/bug-report-form.yml
  .github/ISSUE_TEMPLATE/feature-request-form.yml
  .github/workflows/build.yml
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
  .gitignore
  .gitmessage.txt
  .idea/.gitignore
  .idea/.name
  .idea/4EVER0-BE.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  src/main/java/com/team4ever/backend/BackendApplication.java
  src/main/java/com/team4ever/backend/domain/recommend/controller/RecommendController.java
  src/main/java/com/team4ever/backend/domain/recommend/dto/MultiTurnRequest.java
  src/main/java/com/team4ever/backend/domain/recommend/dto/RecommendedItem.java
  src/main/java/com/team4ever/backend/domain/recommend/service/RecommendService.java
  src/main/java/com/team4ever/backend/global/config/SwaggerConfig.java
  src/main/java/com/team4ever/backend/global/exception/CustomException.java
  src/main/java/com/team4ever/backend/global/exception/ErrorCode.java
  src/main/java/com/team4ever/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/team4ever/backend/global/response/BaseResponse.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/team4ever/backend/BackendApplicationTests.java
Labels: ⚙ Setting

#14 Fix: [EVER-29] yml files updated
  .github/ISSUE_TEMPLATE/bug-report-form.yml
  .github/ISSUE_TEMPLATE/feature-request-form.yml
  .github/workflows/create-jira-issue.yml
Labels: 🐞 BugFix

#15 [Fix] : EVER-29 - Dev에도 업데이트
  .github/ISSUE_TEMPLATE/bug-report-form.yml
  .github/ISSUE_TEMPLATE/feature-request-form.yml
  .github/workflows/create-jira-issue.yml
Labels: 🐞 BugFix

#18 [FIX}: EVER-29 - yml file 전체 업데이트
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: 🐞 BugFix

#19 [FIX] : EVER-29- update main branch
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: 🐞 BugFix, ✅ Test

#20 fix: [EVER-29] finalllllllllllllll updated
  .github/workflows/create-jira-issue.yml
  .idea/modules.xml
  .idea/modules/backend.main.iml
Labels: 🐞 BugFix

#21 [FIX] : EVER-29 main updated
  .github/workflows/create-jira-issue.yml
  .idea/modules.xml
  .idea/modules/backend.main.iml
Labels: 🐞 BugFix

#23 Fix: [EVER-29] parentKey field updated
  .github/workflows/create-jira-issue.yml
Labels: 🐞 BugFix

#24 Fix: [EVER-29] main updated with pr 23
  .github/workflows/create-jira-issue.yml
Labels: ⚙ Setting, 🐞 BugFix, ✅ Test

#26 Fix: [EVER-29] Same id in two job
  .github/workflows/create-jira-issue.yml
Labels: ⚙ Setting, 🐞 BugFix

#27 Fix: {EVER-29] same id in two jobs
  .github/workflows/create-jira-issue.yml
Labels: ⚙ Setting, 🐞 BugFix

#29 Fix: [EVER-29] create-jira-issue naming updated
  .github/workflows/create-jira-issue.yml
Labels: ⚙ Setting, 🐞 BugFix

#33 Fix: [EVER-29] Close-jira-directory fixed
  .github/workflows/close-jira-issue.yml
Labels: ⚙ Setting

#37 Fix: [EVER-29] Create-Close jira key usage updated
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: ⚙ Setting, 🐞 BugFix

#44 FEAT: [EVER-55] CORS filter 설정용 CorsConfig 설정 완료, 로그인, 로그아웃 후 바로 리다이렉팅되게 설정
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-request-template.md
  .idea/dataSources.xml
  .idea/modules.xml
  build.gradle
  src/main/java/com/team4ever/backend/BackendApplication.java
  src/main/java/com/team4ever/backend/global/config/CorsConfig.java
  src/main/java/com/team4ever/backend/global/config/RedisConfig.java
  src/main/java/com/team4ever/backend/global/config/SecurityConfig.java
  src/main/java/com/team4ever/backend/global/config/WebMvcConfig.java
  src/main/java/com/team4ever/backend/global/controller/JwtTokenController.java
  src/main/java/com/team4ever/backend/global/security/CustomOAuth2SuccessHandler.java
  src/main/java/com/team4ever/backend/global/security/CustomOAuth2UserService.java
  src/main/java/com/team4ever/backend/global/security/JwtTokenProvider.java
  src/main/java/com/team4ever/backend/global/security/RedisAuthorizationRequestRepository.java
  src/main/java/com/team4ever/backend/global/security/RedisService.java
  src/main/resources/application.yml
Labels: ⚙ Setting, 📬 API

#49 Feat: [EVER-99] 좋아요 기반 구독 서비스 API 연동
  src/main/java/com/team4ever/backend/domain/chat/controller/ChatController.java
  src/main/java/com/team4ever/backend/domain/chat/dto/ChatLikesRequest.java
  src/main/java/com/team4ever/backend/domain/chat/dto/ChatLikesResponse.java
  src/main/java/com/team4ever/backend/domain/chat/dto/ChatRequest.java
  src/main/java/com/team4ever/backend/domain/chat/dto/ChatResponse.java
  src/main/java/com/team4ever/backend/domain/chat/service/ChatService.java
  src/main/java/com/team4ever/backend/global/config/SecurityConfig.java
Labels: ✨ Feature, 📬 API

#63 Feat: [EVER-108] 미 가입 사용자 회원가입 플로우 편집 완료, 추가로 Auth관련 api들 api uri 변경 완료
  src/main/java/com/team4ever/backend/domain/user/Controller/UserController.java
  src/main/java/com/team4ever/backend/domain/user/Entity/User.java
  src/main/java/com/team4ever/backend/domain/user/Service/UserService.java
  src/main/java/com/team4ever/backend/domain/user/Service/UserServiceImpl.java
  src/main/java/com/team4ever/backend/domain/user/dto/CreateUserRequest.java
  src/main/java/com/team4ever/backend/domain/user/dto/UserResponse.java
  src/main/java/com/team4ever/backend/domain/user/repository/UserRepository.java
  src/main/java/com/team4ever/backend/global/config/SecurityConfig.java
  src/main/java/com/team4ever/backend/global/config/WebMvcConfig.java
  src/main/java/com/team4ever/backend/global/controller/JwtTokenController.java
  src/main/java/com/team4ever/backend/global/security/CustomOAuth2SuccessHandler.java
Labels: ✨ Feature, 📬 API

#64 Feat: [EVER-111] 메인 구독 상품 전체 조회, 카테고리별 라이프스타일 상품 전체 조회 API 개발
  src/main/java/com/team4ever/backend/domain/popups/controller/PopupController.java
  src/main/java/com/team4ever/backend/domain/popups/entity/Popup.java
  src/main/java/com/team4ever/backend/domain/subscriptions/controller/SubscriptionController.java
  src/main/java/com/team4ever/backend/domain/subscriptions/dto/BrandResponse.java
  src/main/java/com/team4ever/backend/domain/subscriptions/dto/SubscribeRequest.java
  src/main/java/com/team4ever/backend/domain/subscriptions/dto/SubscribeResponse.java
  src/main/java/com/team4ever/backend/domain/subscriptions/dto/SubscriptionResponse.java
  src/main/java/com/team4ever/backend/domain/subscriptions/entity/Brand.java
  src/main/java/com/team4ever/backend/domain/subscriptions/entity/Subscription.java
  src/main/java/com/team4ever/backend/domain/subscriptions/entity/SubscriptionCombination.java
  src/main/java/com/team4ever/backend/domain/subscriptions/entity/UserSubscriptionCombination.java
  src/main/java/com/team4ever/backend/domain/subscriptions/repository/BrandRepository.java
  src/main/java/com/team4ever/backend/domain/subscriptions/repository/SubscriptionCombinationRepository.java
  src/main/java/com/team4ever/backend/domain/subscriptions/repository/SubscriptionRepository.java
  src/main/java/com/team4ever/backend/domain/subscriptions/repository/UserSubscriptionCombinationRepository.java
  src/main/java/com/team4ever/backend/domain/subscriptions/service/SubscriptionService.java
  src/main/java/com/team4ever/backend/domain/ubti/service/UBTIService.java
  src/main/java/com/team4ever/backend/global/config/WebMvcConfig.java
  src/main/java/com/team4ever/backend/global/exception/ErrorCode.java
  src/main/java/com/team4ever/backend/global/response/BaseResponse.java
Labels: ✨ Feature

#59 Feat: [EVER-103] 쿠폰 API 전체 기능 구현 및 보안 테스트 설정 추가
  src/main/java/com/team4ever/backend/domain/coupon/controller/CouponController.java
  src/main/java/com/team4ever/backend/domain/coupon/dto/CouponClaimRequest.java
  src/main/java/com/team4ever/backend/domain/coupon/dto/CouponClaimResponse.java
  src/main/java/com/team4ever/backend/domain/coupon/dto/CouponResponse.java
  src/main/java/com/team4ever/backend/domain/coupon/dto/CouponUseResponse.java
  src/main/java/com/team4ever/backend/domain/coupon/entity/Brand.java
  src/main/java/com/team4ever/backend/domain/coupon/entity/Coupon.java
  src/main/java/com/team4ever/backend/domain/coupon/entity/UserCoupon.java
  src/main/java/com/team4ever/backend/domain/coupon/repository/CouponRepository.java
  src/main/java/com/team4ever/backend/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/team4ever/backend/domain/coupon/service/CouponService.java
  src/main/java/com/team4ever/backend/global/config/SecurityConfig.java
  src/main/java/com/team4ever/backend/global/exception/ErrorCode.java
Labels: ✨ Feature, 📬 API

#74 Feat: [EVER-121] JwtInterceptor 구현 및 허용 API EndPoint 설정 완료
  .idea/modules.xml
  src/main/java/com/team4ever/backend/global/config/SecurityConfig.java
  src/main/java/com/team4ever/backend/global/config/WebMvcConfig.java
  src/main/java/com/team4ever/backend/global/controller/JwtTokenController.java
  src/main/java/com/team4ever/backend/global/security/JwtInterceptor.java
  src/main/java/com/team4ever/backend/global/security/RedisService.java
Labels: 📬 API

#77 Feat: [EVER-129] 인증 기반 쿠폰 사용 API 구현
  src/main/java/com/team4ever/backend/domain/coupon/controller/CouponController.java
  src/main/java/com/team4ever/backend/domain/coupon/repository/UserCouponRepository.java
Labels: ✨ Feature, 📬 API

#83 Feat: [EVER-109] upuls benefits api 구현하기
  src/main/java/com/team4ever/backend/domain/benefit/controller/BenefitController.java
  src/main/java/com/team4ever/backend/domain/benefit/dto/BenefitApiResponse.java
  src/main/java/com/team4ever/backend/domain/benefit/dto/BenefitResponse.java
  src/main/java/com/team4ever/backend/domain/benefit/entity/Benefit.java
  src/main/java/com/team4ever/backend/domain/benefit/repository/BenefitRepository.java
  src/main/java/com/team4ever/backend/domain/benefit/service/BenefitService.java
  src/main/java/com/team4ever/backend/domain/popups/controller/PopupController.java
  src/main/java/com/team4ever/backend/domain/popups/dto/PopupResponse.java
Labels: ✨ Feature, 📬 API

#82 Feat: [EVER-137] 내 구독 상품 목록 조회 API 구현
  src/main/java/com/team4ever/backend/BackendApplication.java
  src/main/java/com/team4ever/backend/domain/benefit/controller/BenefitController.java
  src/main/java/com/team4ever/backend/domain/benefit/dto/BenefitApiResponse.java
  src/main/java/com/team4ever/backend/domain/benefit/dto/BenefitResponse.java
  src/main/java/com/team4ever/backend/domain/benefit/entity/Benefit.java
  src/main/java/com/team4ever/backend/domain/benefit/repository/BenefitRepository.java
  src/main/java/com/team4ever/backend/domain/benefit/service/BenefitService.java
  src/main/java/com/team4ever/backend/domain/popups/controller/PopupController.java
  src/main/java/com/team4ever/backend/domain/popups/dto/PopupResponse.java
  src/main/java/com/team4ever/backend/domain/popups/repository/PopupRepository.java
  src/main/java/com/team4ever/backend/domain/popups/service/PopupService.java
  src/main/java/com/team4ever/backend/domain/subscriptions/repository/UserSubscriptionCombinationRepository.java
  src/main/java/com/team4ever/backend/domain/user/Controller/UserController.java
  src/main/java/com/team4ever/backend/domain/user/Service/UserService.java
  src/main/java/com/team4ever/backend/domain/user/Service/UserServiceImpl.java
  src/main/java/com/team4ever/backend/domain/user/dto/UserSubscriptionDto.java
  src/main/java/com/team4ever/backend/domain/user/dto/UserSubscriptionListResponse.java
Labels: ✨ Feature, 📬 API

#85 Feat: [EVER-139] 내 요금제 조회, 변경, 해지 API 구현
  src/main/java/com/team4ever/backend/BackendApplication.java
  src/main/java/com/team4ever/backend/domain/plan/controller/PlanController.java
  src/main/java/com/team4ever/backend/domain/plan/dto/PlanChangeRequest.java
  src/main/java/com/team4ever/backend/domain/plan/dto/PlanChangeResponse.java
  src/main/java/com/team4ever/backend/domain/plan/dto/PlanResponse.java
  src/main/java/com/team4ever/backend/domain/plan/entity/Plan.java
  src/main/java/com/team4ever/backend/domain/plan/repository/PlanRepository.java
  src/main/java/com/team4ever/backend/domain/plan/service/PlanService.java
  src/main/java/com/team4ever/backend/global/exception/ErrorCode.java
Labels: ✨ Feature, 📬 API

#95 Feat: [EVER-147] API 사용자 및 인증 관련 Swagger 한글 summary 추가
  src/main/java/com/team4ever/backend/domain/attendance/controller/AttendanceController.java
  src/main/java/com/team4ever/backend/domain/benefit/controller/BenefitController.java
  src/main/java/com/team4ever/backend/domain/chat/controller/ChatController.java
  src/main/java/com/team4ever/backend/domain/common/couponlike/CouponLike.java
  src/main/java/com/team4ever/backend/domain/plan/controller/PlanController.java
  src/main/java/com/team4ever/backend/domain/popups/controller/PopupController.java
  src/main/java/com/team4ever/backend/domain/subscriptions/controller/SubscriptionController.java
  src/main/java/com/team4ever/backend/domain/ubti/controller/UBTIController.java
  src/main/java/com/team4ever/backend/domain/user/Controller/UserController.java
  src/main/java/com/team4ever/backend/global/controller/JwtTokenController.java
Labels: ✨ Feature, 📬 API

#91 Feat: [EVER-141] 수동 좌표 기반 근처 팝업스토어 조회, IP 위치 기반 내 주변 팝업스토어 조회 API 구현
  src/main/java/com/team4ever/backend/domain/popups/controller/PopupController.java
  src/main/java/com/team4ever/backend/domain/popups/dto/GeolocationResponse.java
  src/main/java/com/team4ever/backend/domain/popups/dto/NearbyPopupResponse.java
  src/main/java/com/team4ever/backend/domain/popups/dto/NearbyPopupsRequest.java
  src/main/java/com/team4ever/backend/domain/popups/dto/UserLocationResponse.java
  src/main/java/com/team4ever/backend/domain/popups/repository/PopupRepository.java
  src/main/java/com/team4ever/backend/domain/popups/service/GeolocationService.java
  src/main/java/com/team4ever/backend/domain/popups/service/PopupService.java
  src/main/java/com/team4ever/backend/global/config/NaverApiConfig.java
  src/main/java/com/team4ever/backend/global/config/RestTemplateConfig.java
  src/main/java/com/team4ever/backend/global/exception/ErrorCode.java
  src/main/java/com/team4ever/backend/global/util/GeoUtils.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API

#98 Feat: [EVER-106] 쿠폰 좋아요 API
  src/main/java/com/team4ever/backend/domain/coupons/controller/CouponLikeController.java
  src/main/java/com/team4ever/backend/domain/coupons/dto/CouponLikeResponseDto.java
  src/main/java/com/team4ever/backend/domain/coupons/dto/CouponSummaryDto.java
  src/main/java/com/team4ever/backend/domain/coupons/service/CouponService.java
Labels: ✨ Feature, 📬 API

#106 Fix: [EVER-157] userController getUser API fixed
  src/main/java/com/team4ever/backend/domain/coupons/controller/CouponLikeController.java
  src/main/java/com/team4ever/backend/domain/coupons/dto/CouponLikeResponseDto.java
  src/main/java/com/team4ever/backend/domain/coupons/dto/CouponSummaryDto.java
  src/main/java/com/team4ever/backend/domain/coupons/service/CouponService.java
  src/main/java/com/team4ever/backend/domain/user/Controller/UserController.java
Labels: 📬 API, 🐞 BugFix

#97 Feat: [EVER-139] 전체 요금제 및 상세 요금제 조회 API 만들기, 요금제 관련 Swagger 정리
  src/main/java/com/team4ever/backend/domain/plan/controller/PlanController.java
  src/main/java/com/team4ever/backend/domain/plan/controller/UserPlanController.java
  src/main/java/com/team4ever/backend/domain/plan/service/PlanService.java
Labels: ✨ Feature, 📬 API

#107 Feat: [EVER-110] 미션 API 구현
  src/main/java/com/team4ever/backend/BackendApplication.java
  src/main/java/com/team4ever/backend/domain/mission/controller/MissionController.java
  src/main/java/com/team4ever/backend/domain/mission/dto/MissionDto.java
  src/main/java/com/team4ever/backend/domain/mission/dto/UserMissionDto.java
  src/main/java/com/team4ever/backend/domain/mission/entity/Mission.java
  src/main/java/com/team4ever/backend/domain/mission/entity/MissionStatus.java
  src/main/java/com/team4ever/backend/domain/mission/entity/MissionType.java
  src/main/java/com/team4ever/backend/domain/mission/entity/UserMission.java
  src/main/java/com/team4ever/backend/domain/mission/repository/MissionRepository.java
  src/main/java/com/team4ever/backend/domain/mission/repository/UserMissionRepository.java
  src/main/java/com/team4ever/backend/domain/mission/service/MissionService.java
  src/main/java/com/team4ever/backend/domain/user/Entity/User.java
  src/main/java/com/team4ever/backend/global/exception/ErrorCode.java
Labels: ✨ Feature, 📬 API

#115 Refactor: [EVER-177] CustomException 적용 및 월별 출석 조회 API 구현
  src/main/java/com/team4ever/backend/domain/attendance/controller/AttendanceController.java
  src/main/java/com/team4ever/backend/domain/attendance/repository/AttendanceRepository.java
  src/main/java/com/team4ever/backend/domain/attendance/service/AttendanceService.java
Labels: ✨ Feature, 🐞 BugFix

#114 [EVER-170] Reverse Geocoding & Google Place API 기반 주변 매장 탐색 기능 추가
  build.gradle
  src/main/java/com/team4ever/backend/BackendApplication.java
  src/main/java/com/team4ever/backend/domain/common/brand/BrandRepository.java
  src/main/java/com/team4ever/backend/domain/coupon/controller/CouponController.java
  src/main/java/com/team4ever/backend/domain/coupon/repository/CouponRepository.java
  src/main/java/com/team4ever/backend/domain/maps/dto/PlaceSearchRequest.java
  src/main/java/com/team4ever/backend/domain/maps/dto/PlaceSearchResponse.java
  src/main/java/com/team4ever/backend/domain/maps/dto/ReverseGeocodeRequest.java
  src/main/java/com/team4ever/backend/domain/maps/dto/ReverseGeocodeResponse.java
  src/main/java/com/team4ever/backend/domain/maps/repository/PlaceRepository.java
  src/main/java/com/team4ever/backend/domain/maps/repository/ReverseGeocodingRepository.java
  src/main/java/com/team4ever/backend/domain/maps/service/PlaceService.java
  src/main/java/com/team4ever/backend/domain/maps/service/ReverseGeocodingService.java
  src/main/java/com/team4ever/backend/domain/user/Controller/UserController.java
  src/main/java/com/team4ever/backend/domain/user/Service/UserServiceImpl.java
  src/main/java/com/team4ever/backend/global/controller/JwtTokenController.java
  src/main/resources/application.yml
Labels: 📬 API

#119 Feat: [EVER-189] 유플투쁠 혜택 API 응답 구조 개선
  src/main/java/com/team4ever/backend/domain/benefit/controller/BenefitController.java
  src/main/java/com/team4ever/backend/domain/benefit/dto/BenefitDetailResponse.java
  src/main/java/com/team4ever/backend/domain/benefit/dto/BenefitPreviewResponse.java
  src/main/java/com/team4ever/backend/domain/benefit/dto/BenefitResponse.java
  src/main/java/com/team4ever/backend/domain/benefit/repository/BenefitRepository.java
  src/main/java/com/team4ever/backend/domain/benefit/service/BenefitService.java
Labels: ✨ Feature, 📬 API

#129 Feat: [EVER-199] 신규 가입자 미션 자동 생성 로직 구현
  src/main/java/com/team4ever/backend/domain/attendance/service/AttendanceService.java
  src/main/java/com/team4ever/backend/domain/mission/entity/UserMission.java
  src/main/java/com/team4ever/backend/domain/mission/service/MissionService.java
  src/main/java/com/team4ever/backend/domain/user/Service/UserServiceImpl.java
  src/main/java/com/team4ever/backend/global/config/CorsConfig.java
Labels: ✨ Feature

#146 Fix: [EVER-268] JWT 필터 로그인 핸들러에 적용 및 세팅 로컬로 초기화
  src/main/java/com/team4ever/backend/global/config/SecurityConfig.java
  src/main/java/com/team4ever/backend/global/controller/JwtTokenController.java
  src/main/java/com/team4ever/backend/global/security/CustomOAuth2SuccessHandler.java
  src/main/java/com/team4ever/backend/global/security/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#150 Refactor: [EVER-278] Place Response and Repository fixed
  src/main/java/com/team4ever/backend/domain/common/brand/BrandRepository.java
  src/main/java/com/team4ever/backend/domain/coupon/controller/CouponController.java
  src/main/java/com/team4ever/backend/domain/coupon/repository/CouponRepository.java
  src/main/java/com/team4ever/backend/domain/coupon/service/CouponService.java
  src/main/java/com/team4ever/backend/domain/maps/dto/PlaceSearchResponse.java
  src/main/java/com/team4ever/backend/domain/maps/repository/PlaceRepository.java
  src/main/resources/application.yml
Labels: 📬 API
